### ISSUE TITLE
[Request] Swapable configs

### ISSUE THREAD

**Issue by kmak7** [DosMike/TF2-PlayerClassDataHook#2]
It would make possible to create fun events where you load one config to lets say increase ammo for classes and later different one to increase hp or speed

Configs could be selected via cvar e.g.: sm_playerclassdata_configfile "pcdh_increasedammo.cfg" and defaults to playerclassdata.cfg

**Comment by DosMike** [comment]
With version 23w23a, change ``sm_tf2playerclassdataconfig`` to whatever path, then run ``sm_playerclassdata_reloadconfig``
